maroverli/urls.py
from django.urls import path, re_path, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.conf import settings

from about import views as about_views
from homepage import views as homepage_views
from blog import views as blog_views
from travel_map import views as travel_views
from media_publicity import views as media_publicity_views
from blog.models import Category
from .sitemap import SITEMAPS


def generate_category_urls():
    category_slugs = Category.objects.values_list("slug", flat=True)
    paths = []
    for slug in category_slugs:
        if slug == "blog":
            continue
        url = f"{slug}/"
        if slug == "portfolio":
            url = ""
        paths.append(
            path(url, blog_views.index, {"category": slug}, name=slug)
        )
    return paths


category_urls = generate_category_urls()


urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),
    path("summernote/", include("django_summernote.urls")),
    path("filer/", include("filer.urls")),
]

urlpatterns += i18n_patterns(
    path("%s/" % settings.MY_ADMIN_URL, admin.site.urls),
    path("", homepage_views.index, name="homepage"),
    path("article/<slug:post_slug>/", blog_views.article, name="article"),
    path("portfolio/", include(category_urls)),
    path("blog/", blog_views.index, {"category": "blog"}, name="blog"),
    path("travel-map/", travel_views.index, name="travel_map"),
    path("about-me/", about_views.index, name="about"),
    path(
        "media-publicity/", media_publicity_views.index, name="media_publicity"
    ),
)

# Uncomment below to support sitemap
urlpatterns += [
   re_path(r"^sitemap\.xml/$",
           sitemap,
           {"sitemaps": SITEMAPS, "template_name": "sitemap.xml"},
           name="django.contrib.sitemaps.views.sitemap"
           )
]

# Uncomment below to serve uploaded files and custom error pages
if settings.DEBUG:
    from django.views.static import serve
    from django.views.defaults import page_not_found, server_error

    urlpatterns += [
        re_path(
            r"^media-file/(?P<path>.*)",
            serve,
            {"document_root": settings.MEDIA_ROOT},
        ),
        re_path(
            r"^favicon/(?P<path>.*)",
            serve,
            {"document_root": settings.ROOT.joinpath("favicon")},
        ),
    ]

    urlpatterns += [
        path("404/", page_not_found, {"exception": ""}),
        path("500/", server_error),
    ]

# path("portfolio/", include([
#     path("", blog_views.portfolio, {"category": "portfolio"}, name="portfolio"),
#     path("features/", blog_views.portfolio, {"category": "features"}, name="features"),
#     path("food/", blog_views.portfolio, {"category": "food"}, name="food"),
#     path("special-projects/", blog_views.portfolio, {"category": "special-projects"}, name="special-projects"),
# ])),

about/models.py
from textwrap import shorten

from django.db import models
from django.utils.translation import get_language
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.utils.html import strip_tags
from django.utils.translation import ugettext_lazy as _


class TimelineEntry(models.Model):
    is_active = models.BooleanField(default=True)
    year = models.CharField(max_length=4)
    icon = models.CharField(
        max_length=30,
        help_text="Go to <a href='https://feathericons.com'>feather icons</a> "
        "and enter the name of the icon you want.<br>Example: if "
        "you want the alert-circle icon, simply write alert-circle.",
    )
    text = models.TextField()
    order = models.PositiveSmallIntegerField(default=0)

    class Meta:
        verbose_name = "Timeline Entry"
        verbose_name_plural = "Timeline Entries"
        ordering = ["order"]

    def __str__(self):
        return self.year

    def shorten_text(self):
        return strip_tags(shorten(self.text.strip(), width=150, placeholder="..."))

    def icon_path(self):
        return static(f"img/icons/svg/{self.icon.strip()}.svg")


class AboutCommonABC(models.Model):

    LETTER_A = "A"
    LETTER_B = "B"
    LETTER_O = "O"
    LETTER_U = "U"
    LETTER_T = "T"
    LETTER_M = "M"
    LETTER_E = "E"

    LETTER_CHOICES = (
        (LETTER_A, _("A")),
        (LETTER_B, _("B")),
        (LETTER_O, _("O")),
        (LETTER_U, _("U")),
        (LETTER_T, _("T")),
        (LETTER_M, _("M")),
        (LETTER_E, _("E")),
    )

    header = models.CharField(max_length=30)
    letter = models.CharField(max_length=1, choices=LETTER_CHOICES)
    letter_image = models.ImageField(
        upload_to="img/letters", help_text="Image height must be 250px."
    )

    class Meta:
        abstract = True

    def __str__(self):
        return self.header

    def pre_letter(self):
        return f"{self.letter}_{get_language().upper()}"

    def get_img_url(self):
        return self.letter_image.url


class AboutCommonProfile(AboutCommonABC):
    class Meta:
        verbose_name = "Profile"
        verbose_name_plural = "Profiles"


class AboutProfile(models.Model):
    text = models.TextField()
    about = models.ForeignKey(
        AboutCommonProfile, on_delete=models.CASCADE, related_name="profiles"
    )

    def __str__(self):
        return shorten(self.text, width=50, placeholder="...")


class AboutCommonScopeOfWork(AboutCommonABC):
    class Meta:
        verbose_name = "Scope of Work"
        verbose_name_plural = "Scopes of Work"


class AboutScopeOfWork(models.Model):
    text = models.TextField()
    icon = models.CharField(
        max_length=30,
        help_text="Go to <a href='https://feathericons.com'>feather icons</a> "
        "and enter the name of the icon you want.<br>Example: if "
        "you want the alert-circle icon, simply write alert-circle.",
    )
    order = models.PositiveSmallIntegerField(default=0)
    about = models.ForeignKey(
        AboutCommonScopeOfWork,
        on_delete=models.CASCADE,
        related_name="scopes_of_work",
    )

    class Meta:
        ordering = ["order"]

    def __str__(self):
        return shorten(self.text, width=30, placeholder="...")

    def icon_path(self):
        return static(f"img/icons/svg/{self.icon.strip()}.svg")


class AboutCommonSkill(AboutCommonABC):
    class Meta:
        verbose_name = "Skill"
        verbose_name_plural = "Skills"


class AboutSkill(models.Model):
    skill = models.CharField(max_length=50)
    percentage = models.PositiveSmallIntegerField(
        help_text="A number between 0 - 100."
    )
    order = models.PositiveSmallIntegerField(default=0)
    about = models.ForeignKey(
        AboutCommonSkill, on_delete=models.CASCADE, related_name="skills"
    )

    class Meta:
        ordering = ["order"]

    def __str__(self):
        return self.skill


class AboutCommonExperience(AboutCommonABC):
    class Meta:
        verbose_name = "Experience"
        verbose_name_plural = "Experiences"


class AboutExperience(models.Model):
    year = models.CharField(max_length=20)
    place = models.CharField(max_length=50)
    job_title = models.CharField(max_length=100)
    job_employer = models.CharField(max_length=70)
    order = models.PositiveSmallIntegerField(default=0)
    about = models.ForeignKey(AboutCommonExperience, on_delete=models.CASCADE,
                              related_name="experiences")

    class Meta:
        ordering = ["order"]

    def __str__(self):
        return f"{self.year} | {self.place}"


class AboutExperienceLanguage(models.Model):
    text = models.CharField(max_length=50)
    percentage = models.PositiveSmallIntegerField(
        help_text="A number between 0 - 100."
    )
    order = models.PositiveSmallIntegerField(default=0)

    class Meta:
        verbose_name = "lLnguage"
        verbose_name_plural = "Languages"
        ordering = ["order"]

    def __str__(self):
        return self.text


class AboutCommonEducation(AboutCommonABC):
    class Meta:
        verbose_name = "Education"
        verbose_name_plural = "Educations"


class AboutEducation(models.Model):
    years = models.CharField(max_length=20)
    title = models.CharField(max_length=100)
    university = models.CharField(max_length=80)
    icon = models.CharField(
        max_length=30,
        help_text="Go to <a href='https://feathericons.com'>feather icons</a> "
                  "and enter the name of the icon you want.<br>Example: if "
                  "you want the alert-circle icon, simply write alert-circle.",
    )
    order = models.PositiveSmallIntegerField(default=0)
    about = models.ForeignKey(AboutCommonEducation, on_delete=models.CASCADE,
                              related_name="educations")

    class Meta:
        ordering = ["order"]

    def __str__(self):
        return self.title

    def icon_path(self):
        return static(f"img/icons/svg/{self.icon.strip()}.svg")


class AboutCommonAchievement(AboutCommonABC):
    class Meta:
        verbose_name = "Achievement"
        verbose_name_plural = "Achievements"


class AboutAchievement(models.Model):
    text = models.TextField()
    icon = models.CharField(
        max_length=30,
        help_text="Go to <a href='https://feathericons.com'>feather icons</a> "
                  "and enter the name of the icon you want.<br>Example: if "
                  "you want the alert-circle icon, simply write alert-circle.",
    )
    order = models.PositiveSmallIntegerField(default=0)
    about = models.ForeignKey(AboutCommonAchievement, on_delete=models.CASCADE,
                              related_name="achievements")

    class Meta:
        ordering = ["order"]

    def __str__(self):
        return shorten(self.text, width=50, placeholder="...")

    def icon_path(self):
        return static(f"img/icons/svg/{self.icon.strip()}.svg")


class AboutCommonFact(AboutCommonABC):
    class Meta:
        verbose_name = "Facts"
        verbose_name_plural = "Facts"


class AboutFact(models.Model):
    text = models.TextField()
    icon = models.CharField(
        max_length=30,
        help_text="Go to <a href='https://feathericons.com'>feather icons</a> "
        "and enter the name of the icon you want.<br>Example: if "
        "you want the alert-circle icon, simply write alert-circle.",
    )
    order = models.PositiveSmallIntegerField(default=0)
    about = models.ForeignKey(
        AboutCommonFact,
        on_delete=models.CASCADE,
        related_name="scopes_of_work",
    )

    class Meta:
        verbose_name = "Fact"
        verbose_name_plural = "Facts"
        ordering = ["order"]

    def __str__(self):
        return shorten(self.text, width=30, placeholder="...")

    def icon_path(self):
        return static(f"img/icons/svg/{self.icon.strip()}.svg")

about/views.py
from django.shortcuts import render
from django.utils.translation import ugettext_lazy as _

from .models import (
    TimelineEntry,
    AboutProfile,
    AboutScopeOfWork,
    AboutSkill,
    AboutExperience,
    AboutExperienceLanguage,
    AboutEducation,
    AboutAchievement,
    AboutFact,
)


def index(request):
    timeline_entries = TimelineEntry.objects.filter(is_active=True)
    profile = AboutProfile.objects.first()
    scopes = AboutScopeOfWork.objects.all()
    skills = AboutSkill.objects.all()
    experiences = AboutExperience.objects.all()
    languages = AboutExperienceLanguage.objects.all()
    educations = AboutEducation.objects.all()
    achievements = AboutAchievement.objects.all()
    facts = AboutFact.objects.all()
    meta_description = _("Dare to Dream Big! Cause Every Big dream is a new "
                         "goal and every difficulty, an opportunity to learn. "
                         "Here is my life story! "
                         "Available for new challenges!")
    page_title = _("About Me")
    return render(
        request,
        "about/index.html",
        {
            "timeline_entries": timeline_entries,
            "profile": profile,
            "scopes": scopes,
            "skills": skills,
            "experiences": experiences,
            "languages": languages,
            "educations": educations,
            "achievements": achievements,
            "facts": facts,
            "meta_description": meta_description,
            "page_title": page_title,
        },
    )

templates/about/a.html
{# PROFILE #}

<div class="flip__box about__box">
	<div class="card">
		<div class="front">
			<img class="lazy"
			     src="{{ LETTER_PLACEHOLDER }}"
			     data-src="{{ profile.about.get_img_url() }}"
			     alt="{{ _('letter') }} {{ profile.about.get_letter_display() }}"
			>
		</div>
		<div class="back before__back__a">
			<div class="back__content">
				<h2>{{ profile.about.header }}!</h2>
				<p>{{ profile.text }}</p>
			</div>
		</div>
	</div>
</div>


{% block extra_inline_styles %}
<style>
.before__back__a::before {
	background-image: url('{{ profile.about.get_img_url() }}');
}
</style>
{% endblock %}

templates/about/b.html
{# SCOPE OF WORK #}

<div class="flip__box about__box">
	<div class="card">
		{% set scp=scopes.first() %}
		<div class="front">
			<img
				class="lazy"
				src="{{ LETTER_PLACEHOLDER }}"
				data-src="{{ scp.about.get_img_url() }}"
				alt="{{ _('letter') }} {{ scp.about.get_letter_display() }}"
			>
		</div>
		<div class="back before__back__b">
			<div class="back__content">
				<h2>{{ scp.about.header }}</h2>
				<ul>
					{% for scope in scopes %}
						<li class="scope__wrapper">
							<span class="scope__icon" style="background:url({{ scope.icon_path() }}) no-repeat"></span>
							<span class="scope__text">{{ scope.text }}</span>
						</li>
					{% endfor %}
				</ul>
			</div>
		</div>
	</div>
</div>


{% block extra_inline_styles %}
<style>
.before__back__b::before {
	background-image: url('{{ scp.about.get_img_url() }}');
}
</style>
{% endblock %}

templates/about/e.html
{# SOME FACTS #}

<div class="flip__box about__box">
	<div class="card">
		{% set ff=facts.first() %}
		<div class="front">
			<img
				class="lazy"
				src="{{ LETTER_PLACEHOLDER }}"
				data-src="{{ ff.about.get_img_url() }}"
				alt="{{ _('letter') }} {{ ff.about.get_letter_display() }}"
			>
		</div>
		<div class="back before__back__e">
			<div class="back__content">
				<h2>{{ ff.about.header }}</h2>
				<ul>
					{% for f in facts %}
						<li class="scope__wrapper">
							<span class="scope__icon" style="background:url({{ f.icon_path() }}) no-repeat"></span>
							<span class="scope__text">{{ f.text }}</span>
						</li>
					{% endfor %}
				</ul>
			</div>
		</div>
	</div>
</div>


{% block extra_inline_styles %}
<style>
.before__back__e::before {
	background-image: url('{{ ff.about.get_img_url() }}');
}
</style>
{% endblock %}

templates/about/index.html
{% extends "base/index.html" %}

{% block content_wrapper_extra_classes %} aboutme{% endblock %}

{% block extra_styles %}
<link rel="stylesheet" href="https://unpkg.com/simplebar@5.1.0/dist/simplebar.css">
<link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
{% endblock %}

{% block meta_social %}
{{ super() }}
<meta property="og:description"  content="{{ meta_description }}" />
<meta property="og:image"        content="{{ request.build_absolute_uri(static('img/social/about_me.jpg')) }}" />
<meta property="og:image:width"  content="1920" />
<meta property="og:image:height" content="1422" />
{% endblock %}

{% block extra_js %}
<script src="https://unpkg.com/simplebar@5.1.0/dist/simplebar.min.js" defer></script>
<script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js" defer></script>
<script src="{{ static('js/about.min.js') }}" defer></script>
{% endblock %}


{% block about %}

	<div class="about__container">
		<div class="about__top__container">
			{% set LETTER_PLACEHOLDER="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mOMNgYAAO8AkE7ayCwAAAAASUVORK5CYII=" %}
			{% include "about/a.html" %}
			{% include "about/b.html" %}
			{% include "about/o.html" %}
			{% include "about/u.html" %}
			{% include "about/t.html" %}
			{% include "about/m.html" %}
			{% include "about/e.html" %}
		</div>
		<div class="about__bottom__container">
			{% include "about/timeline.html" %}
		</div>
	</div>

{% endblock %}

templates/about/m.html
{# ACHIEVEMENTS #}

<div class="flip__box about__box">
	<div class="card">
		{% set ach=achievements.first() %}
		<div class="front">
			<img
				class="lazy"
				src="{{ LETTER_PLACEHOLDER }}"
				data-src="{{ ach.about.get_img_url() }}"
				alt="{{ _('letter') }} {{ ach.about.get_letter_display() }}"
			>
		</div>
		<div class="back before__back__m">
			<div class="back__content">
				<h2>{{ ach.about.header }}</h2>
				<ul>
					{% for a in achievements %}
						<li class="achievement__wrapper">
							<span class="achievement__icon" style="background:url({{ a.icon_path() }}) no-repeat"></span>
							<span class="achievements__text">{{ a.text|safe }}</span>
						</li>
					{% endfor %}
				</ul>
			</div>
		</div>
	</div>
</div>


{% block extra_inline_styles %}
<style>
.before__back__m::before {
	background-image: url('{{ ach.about.get_img_url() }}');
}
</style>
{% endblock %}

templates/about/o.html
{# SKILLS #}

<div class="flip__box about__box">
	<div class="card">
		{% set skil=skills.first() %}
		<div class="front">
			<img
				class="lazy"
				src="{{ LETTER_PLACEHOLDER }}"
				data-src="{{ skil.about.get_img_url() }}"
				alt="{{ _('letter') }} {{ skil.about.get_letter_display() }}"
			>
		</div>
		<div class="back before__back__o">
			<div class="back__content">
				<h2>{{ skil.about.header }}</h2>
				<ul>
					{% for skill in skills %}
						<li class="skill__wrapper">
							<p class="skill__text__wrapper">
								<span class="skill__text">{{ skill }}</span>
								<span class="skill__percent">{{ skill.percentage }}%</span>
							</p>
							<div class="skill__bar__wrapper">
								<span class="skill__bar" style="width: {{ skill.percentage }}%;"></span>
							</div>
						</li>
					{% endfor %}
					{% if languages %}
						<li class="language__title">{{ _("Languages") }}</li>
					{% for lang in languages %}
						<li class="skill__wrapper">
							<p class="skill__text__wrapper">
								<span class="skill__text">{{ lang.text }}</span>
								<span class="skill__percent">{{ lang.percentage }}%</span>
							</p>
							<div class="skill__bar__wrapper">
								<span class="skill__bar" style="width: {{ lang.percentage }}%;"></span>
							</div>
						</li>
					{% endfor %}
					{% endif %}
				</ul>
			</div>
		</div>
	</div>
</div>


{% block extra_inline_styles %}
<style>
.before__back__o::before {
	background-image: url('{{ skil.about.get_img_url() }}');
}
</style>
{% endblock %}

templates/about/t.html
{# EDUCATION #}

<div class="flip__box about__box">
	<div class="card">
		{% set edu=educations.first() %}
		<div class="front">
			<img
				class="lazy"
				src="{{ LETTER_PLACEHOLDER }}"
				data-src="{{ edu.about.get_img_url() }}"
				alt="{{ _('letter') }} {{ edu.about.get_letter_display() }}"
			>
		</div>
		<div class="back before__back__t">
			<div class="back__content">
				<h2>{{ edu.about.header }}</h2>
				<ul>
					{% for e in educations %}
						<li class="education__wrapper">
							<div class="education__icon" style="background-image:url('{{ e.icon_path() }}')"></div>
							<div class="education__text">
								<span>{{ e.years }}</span>
								<span>{{ e.title }}</span>
								<span>{{ e.university }}</span>
							</div>
						</li>
					{% endfor %}
				</ul>
			</div>
		</div>
	</div>
</div>


{% block extra_inline_styles %}
<style>
.before__back__t::before {
	background-image: url('{{ edu.about.get_img_url() }}');
}
</style>
{% endblock %}

templates/about/timeline.html
{% for entry in timeline_entries %}
	<div class="timeline__entry carousel-cell">
		<div class="timeline__entry__container">
			<div class="timeline__icon"><img src="{{ entry.icon_path() }}" alt=""></div>
			<div class="timeline__year">{{ entry.year }}</div>
			<div class="timeline__content">
				<div class="circle"></div>
				<div class="article__container">
					<article>{{ entry.text|safe }}</article>
				</div>
			</div>
		</div>
	</div>
{% endfor %}

templates/about/u.html
{# EXPERIENCE #}

<div class="flip__box about__box">
	<div class="card">
		{% set exp=experiences.first() %}
		<div class="front">
			<img
				class="lazy"
				src="{{ LETTER_PLACEHOLDER }}"
				data-src="{{ exp.about.get_img_url() }}"
				alt="{{ _('letter') }} {{ exp.about.get_letter_display() }}"
			>
		</div>
		<div class="back before__back__u">
			<div class="back__content">
				<h2>{{ exp.about.header }}</h2>
				<ul>
					{% for e in experiences %}
						<li class="exp__wrapper">
							<span>{{ e.year }} ({{ e.place }})</span>
							<span>{{ e.job_title }}</span>
							<span>{{ e.job_employer }}</span>
						</li>
					{% endfor %}
				</ul>
			</div>
		</div>
	</div>
</div>


{% block extra_inline_styles %}
<style>
.before__back__u::before {
	background-image: url('{{ exp.about.get_img_url() }}');
}
</style>
{% endblock %}